#!/usr/bin/env python3

"""f/π is an open source, catalog-oriented digital asset managemt tool."""

from optparse import OptionParser

import cli


def start_gui(option, _, parameter, opt_parser):
    """Start f/π GUI version."""
    raise NotImplementedError("f/π GUI not yet implemented.")


def _main():
    desc = """f/π is an open source, catalog-oriented digital asset managemt tool.
            The available commands are: catalog, ingest and info."""

    opt_parser = OptionParser(usage="%prog command catalog [options]",
                              version="f/π version α-1",
                              description=desc)
    opt_parser.add_option("", "--gui", action="callback", callback=start_gui,
                          help="start f/π GUI version.")

    options, args = cli.configure_option_parser(opt_parser).parse_args()

    if len(args) < 2:
        msg = "You must provide a catalog name or file."
        if len(args) < 1:
            msg = "You must provide the command to execute.\n" + msg
        print(msg + "\n")
        opt_parser.print_usage()
        exit(1)
    else:
        try:
            cli.execute(options, args)
        except Exception as e:
            print("ERROR: %s\n" % e)
            opt_parser.print_help()
            exit(1)


if __name__ == "__main__":
    _main()
