#!/usr/bin/env python3

"""f/π is an open source, catalog-oriented digital asset managemt tool."""

from optparse import OptionParser

import cli
import cli_opt


def start_gui(option, string, parameter, opt_parser):
    """Start f/π GUI version."""
    raise NotImplementedError("f/π GUI not yet implemented.")


def _main():
    desc = """f/π is an open source, catalog-oriented digital asset managemt tool.
            The available commands are: catalog, ingest and info."""
    usage_string = "%prog command catalog [options] file|directory ..."
    
    opt_parser = OptionParser(usage=usage_string,
                              version="f/π version α-1",
                              description=desc)
    opt_parser.add_option("", "--gui", action="callback", callback=start_gui,
                          help="start f/π GUI version.")

    opt_parser = cli_opt.configure_option_parser(opt_parser)

    try:
        options, args = opt_parser.parse_args()

        if len(args) == 0:
            opt_parser.print_help()
            exit(1)
        elif len(args) < 2:
            msg = "You must provide a command and a catalog name or file."
            raise Exception(msg)
        else:
            cli.execute(options, args)
    except Exception as e:
        # raise e
        print("ERROR: %s\n" % e)
        opt_parser.print_usage()
        exit(1)


if __name__ == "__main__":
    _main()
